### ISSUE TITLE
docker-compose up seems to be endlessly looping

### ISSUE THREAD

**Issue by adf-ncgr** [abretaud/docker-lis-gcv#1]
Hi-
I tried a git clone of this followed by docker-compose up and after the set-up process seemed to be running for a very long time I realized that it was going through the same sequence of steps over and over; here is the bit that seems to be getting repeated for me, it seems to be a sort of cyclic dependency where it wants to get tripal_analysis_expression as part of the tripal install, but then 
sees tripal as a dependency of tripal_analysis_expression and starts installing tripal over again.
I may be doing something stupid though; let me know if so! Technically, the GCV itself doesn't really have any tripal dependency, but maybe that is the most convenient way of getting chado installed, or maybe this is to create a single container with both GCV and the tripal_phylotree present?

tripal_1  | Loading version_control engine.                                         [notice]
tripal_1  | Loading package_handler engine.                                         [notice]
tripal_1  | Executing: wget --version
tripal_1  | Loading release_info engine.                                            [notice]
tripal_1  | Downloading release history from                                        [notice]
tripal_1  | https://updates.drupal.org/release-history/tripal/7.x
tripal_1  | /root/.drush/cache/download/https---updates.drupal.org-release-history-tripal-7.x   [notice]
tripal_1  | retrieved from cache.
tripal_1  | Undefined variable: recommended_major Project.php:397                   [notice]
tripal_1  | Undefined variable: recommended_major Project.php:397                   [notice]
tripal_1  | Downloading project tripal ...                                          [notice]
tripal_1  | /root/.drush/cache/download/https---ftp.drupal.org-files-projects-tripal-7.x-2.1.tar.gz   [notice]
tripal_1  | retrieved from cache.
tripal_1  | Downloading tripal-7.x-2.1.tar.gz was successful.                       [notice]
tripal_1  | Md5 checksum of tripal-7.x-2.1.tar.gz verified.                         [notice]
tripal_1  | Executing: tar  -C /tmp/drush_tmp_1522536259_5ac00f439763d -xzf tripal-7.x-2.1.tar.gz
tripal_1  | Executing: tar -tzf tripal-7.x-2.1.tar.gz
tripal_1  | Using destination directory /var/www/html/sites/all/modules             [notice]
tripal_1  | Executing: svn info /var/www/html/sites/all/modules
tripal_1  | Executing: bzr root /var/www/html/sites/all/modules
tripal_1  | Install location /var/www/html/sites/all/modules/tripal already exists. Do you want to overwrite it? (y/n): y
tripal_1  | Project tripal (7.x-2.1) downloaded to                                 [success]
tripal_1  | /var/www/html/sites/all/modules/tripal.
tripal_1  | Project tripal contains 19 modules: tripal_bulk_loader, tripal_cv, tripal_pub, tripal_views, tripal_phylogeny, tripal_example, tripal_phenotype, tripal_analysis, tripal_feature, tripal_stock, tripal_organism, tripal_contact, tripal_featuremap, tripal_project, tripal_core, tripal_library, tripal_db, tripal_genetic, tripal_natural_diversity.
tripal_1  | Command dispatch complete                                               [notice]
tripal_1  | The following projects have unmet dependencies:                             [ok]
tripal_1  | tripal_analysis_expression requires tripal
tripal_1  | Would you like to download them? (y/n): y
tripal_1  | Calling proc_open(/usr/local/bin/php /root/.composer/vendor/drush/drush/drush.php --php=/usr/local/bin/php  --verbose --root=/var/www/html --uri=http://default  pm-download tripal 2>&1);
tripal_1  | Executing: PGPASSFILE=/tmp/drush_eBHvZk psql -q --dbname=postgres --host=postgres --port=5432 --username=postgres  --no-align --field-separator='	' --pset tuples_only=on --file /tmp/drush_GcRTiM
tripal_1  | Executing: PGPASSFILE=/tmp/drush_mykWAs psql -q --dbname=postgres --host=postgres --port=5432 --username=postgres  --no-align --field-separator='	' --pset tuples_only=on --file /tmp/drush_YlTcNT
tripal_1  | Loading version_control engine.                                         [notice]

**Comment by abretaud** [comment]
Thanks for testing!
There was indeed a dependency loop due to tripal_analysis_expression module.
I just updated the tripal docker image to exclude this module until we find a better solution.
To test it, you'll need to update the docker image with `docker pull erasche/tripal` and then `docker-compose down; docker-compose up -d` to restart everything.

The tripal container is not strictly needed, this was to be able to test tripal_phylotree too. You can safely remove the tripal section in docker-compose.yml + set INSTALL_CHADO_SCHEMA to 1 (to make the chado container install itself the chado schema instead of letting tripal do it)

**Comment by adf-ncgr** [comment]
Thanks, that got me up and running, I think; at least, I get the instructions page when I access
http://localhost:8100 
note that the README may be a little confusing on that point (at least, it confused me); I had started off trying to use : 
|GCV_URL|External URL to access GCV|http://localhost:8000|
but I think the 8000 port is just where the service calls to the django application are being served?
|SERVICES_URL|External URL to access GCV API|http://localhost:8000/services|

anyway, this looks like a great start! Am I correct in thinking that this currently has no test data for GCV to access? Did you have a plan for that or is it something we should try to help with? 

thanks again, it's great to have someone else working on this with us!

**Comment by abretaud** [comment]
Thanks, I have clarified the README, I hope it's clearer like this

For the moment I have no public test data (only some not-yet released genomes on our instance), but it would be very good to have some, contributions are welcome of course :)

**Comment by adf-ncgr** [comment]
thanks, your changes look good to me. I think I'll go ahead and close this issue and start another one regarding provisioning it with some sample data.
